print("Hello Good Morning!")
print("Wake Up by 7:30 am or 8:00 am")
print("Drink atleast half or full litre of water")
print("Do Half an hour excersise")
print("Get ready to work")
print("Start from office by 7:00 or 7:30")
print("Have snacks or lunch")
print("Do one hour of personal work")
print("Go to bed by 11:00 or max by 11:30pm")
